[phases.setup]
aptPkgs = ["tesseract-ocr", "poppler-utils", "libgl1-mesa-glx", "libglib2.0-0"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn -w 2 -b 0.0.0.0:$PORT run:app --timeout 120 --preload"