services:
  - type: web
    name: genhealth-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT run:app
    plan: free
    healthCheckPath: /health